### ISSUE TITLE
Items API Service returns 500 Internal Server Error

### ISSUE THREAD

**Issue by jobinthomasnypl** [NYPL-discovery/discovery-general#16]

**Comment by jobinthomasnypl** [comment]
The Sierra harvester is now posting item information that it gets from Sierra to the Items API Service. However, from there are a lot of 500 Internal Server Errors that are being returned from the Items API Service.

Given below are some of the failures:

org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1203) at java.lang.Thread.run(Thread.java:745) 2016-10-17 09:32:10,889 (ItemIdUpdater.java:73) ERROR org.nypl.catalog.updater.item.ItemIdUpdater - Failed processing itemId - 17118523 org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:84) at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) at org.nypl.catalog.updater.item.ItemIdUpdater.callItemApi(ItemIdUpdater.java:112) at org.nypl.catalog.updater.item.ItemIdUpdater.postItemInfoToApi(ItemIdUpdater.java:89) at org.nypl.catalog.updater.item.ItemIdUpdater.processMessage(ItemIdUpdater.java:56) at 

org.nypl.catalog.updater.item.ItemIdUpdater - Failed processing itemId - 18658475 org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:84) at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) at org.nypl.catalog.updater.item.ItemIdUpdater.callItemApi(ItemIdUpdater.java:112) at org.nypl.catalog.updater.item.ItemIdUpdater.postItemInfoToApi(ItemIdUpdater.java:89) at org.nypl.catalog.updater.item.ItemIdUpdater.processMessage(ItemIdUpdater.java:56) at 

org.nypl.catalog.updater.item.ItemIdUpdater - Failed processing itemId - 18999380 org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:84) at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) at org.nypl.catalog.updater.item.ItemIdUpdater.callItemApi(ItemIdUpdater.java:112) at org.nypl.catalog.updater.item.ItemIdUpdater.postItemInfoToApi(ItemIdUpdater.java:89) at org.nypl.catalog.updater.item.ItemIdUpdater.processMessage(ItemIdUpdater.java:56) at

**Comment by kfriedman** [comment]
Created a Slack channel #service-logging and also rollback functionality for API errors. Going to close this out until we get more information and re-open new tickets.
