### ISSUE TITLE
Performance of NYPL's Bib/Item API service

### ISSUE THREAD

**Issue by jobinthomasnypl** [NYPL-discovery/discovery-general#26]
The Sierra consumer and the recap consumers seem to be very slow. Need to make sure if the slowness is because of NYPL's bib/item api service

**Comment by kfriedman** [comment]
I just did a quick load test to POST api/v0.1/items and with about 10 items/second without too much trouble:

https://loader.io/reports/c5786e9bcd8843b46418a314d1efc3b2/results/3b5537c55edb0c22b9b9e837898ff928

Is that not performant enough? If not, then we may need to increase the instance size or do further investigations.

**Comment by kfriedman** [comment]
Let's talk about what performance you might need and then we can scale accordingly.

**Comment by kfriedman** [comment]
I just did a quick load test on POST api/v0.1/bibs and got about the same result:

https://loader.io/reports/bb85f3a92c7c3fc75deed6611a5f32ce/results/84e16e3a39cee2d5382f2c6f37b12c82

Was able to do about 10/bibs a second.

Let's investigate?

**Comment by jobinthomasnypl** [comment]
Hey Kevin,
Can you run both items and bibs together and post your results. That's the test we are running right now. 

Thanks,
Jobin

**Comment by kfriedman** [comment]
Yes. Let's talk later. 

BTW, I think this is a good model for how service owners and clients can collaborate together to create a service SLA. We should discuss this process with @jvarghese01.

**Comment by jobinthomasnypl** [comment]
At present, I have Sierra items posting to the api and also recap bibs posting to the api. Yesterday while Kevin was at my desk, I showed him that when I stop posting to items, posting to bibs is faster.

**Comment by kfriedman** [comment]
Bib testing:
http://bit.ly/2fnsxzK
Item testing:
http://bit.ly/2eVboeb

Bib POST SLA:
Average Response: 250ms
Minimum: 26 posts/sec 

Item POST SLA:
Average Response: 250ms
Minimum: 36 posts/sec

**Comment by kfriedman** [comment]
Going to close this out.
