### ISSUE TITLE
Update the ReCAP harvester to support leader and control field varFields

### ISSUE THREAD

**Issue by thisismattmiller** [NYPL-discovery/discovery-general#35]
Two fields inside the bib->content->collection->record ReCAP record need to be added to the varFields sierra format. the "leader" and "controlfield", they look like this:
`<leader>01233cas a2200373I  4500</leader>`
`<controlfield tag="001">1</controlfield>`
`<controlfield tag="005">20130405104912.0</controlfield>`
`<controlfield tag="008">860123c19069999ii wr p      f0   a0eng d</controlfield>`

These need to be converted to sierra varfield format so for 001/005/008 it would look like:
```
{
  fieldTag: "y",
  marcTag: "008",
  ind1: " ",
  ind2: " ",
  content: "751112s1858 maucdf 000 0beng namI "
}
```
the leader will look like this:
```
{
fieldTag: "_",
content: "00000nam 2200325I 4500"
}
```

Once that is done and pushing we need to delete the current bib topic.

**Comment by jobinthomasnypl** [comment]
Done
