### ISSUE TITLE
launch ES cluster in aws

### ISSUE THREAD

**Issue by nonword** [NYPL-discovery/discovery-general#45]

**Comment by 0ara0** [comment]
Assigning to Kevin who'll ask Ho-Ling to set this up.

**Comment by kfriedman** [comment]
Unfortunately, Ho-Ling is probably going to be out the next 90 days for jury duty. We'll probably need to figure something else out... 😦

**Comment by 0ara0** [comment]
Paul got a basic instance up but w/o tuning, documentation as a new service to review with Ops.
