### ISSUE TITLE
Test sierra test api v3 to ensure index against updatedDate works as expected

### ISSUE THREAD

**Issue by jobinthomasnypl** [NYPL-discovery/discovery-general#46]
III has made changes to the updatedDate column and we have to test and ensure that the items api call is going to be faster.

**Comment by jobinthomasnypl** [comment]
Test api server:

For 42.396 items - start at 11:45:47 end at 11:48:58
Total time - 3 mins 11 secs


Prod api server:

For 42,000 items - start at 12:15:12 end at 12:21:49
Total Time - 6 mins 37 secs

**Comment by jobinthomasnypl** [comment]
As part of the test, I am noticing that there are more than 10 sec delay for createdDate in test server, but in prod api server its less.

**Comment by jobinthomasnypl** [comment]
@thisismattmiller, @kfriedman  - the action items here are :

1) We see more than 2 times faster speed. Hence move on with whatever is the next step to get this into prod

2) Let them know that the time for every api call increases as the size increse

3) Test server's createdDate querying is same as prod, because prod has better performance than test server for querying createdDate.

**Comment by kfriedman** [comment]
This is great, thanks Jobin. I'm guessing the incremental increase is a memory issue; not sure what we can do about that but it's worth mentioning to Innovative. Nice work.

**Comment by jobinthomasnypl** [comment]
@kfriedman, memory issue on their side?

**Comment by kfriedman** [comment]
Yes, that's what I'm thinking. Let's see what they say.

**Comment by jobinthomasnypl** [comment]
After back porting the prod db to test server, the results are as follows:

For 42.000 items -
84 api calls
start at 10:05:57 end at 10:06:33
Total time - 36 secs
Each api call - 0.428 secs

For 80.000 items -
160 api calls
start at 10:05:57 end at 10:07:14
Total time - 77 secs
Each api call - 0.481 secs

For 231.000 items -
462 api calls
start at 10:05:57 end at 10:11:01
Total time - 5 mins and 4 secs
Each api call - 0.658 secs

For 500.000 items -
1000 api calls
start at 10:05:57 end at 10:24:46
Total time - 18mins and 49 secs
Each api call - 1.129 secs

For 750.000 items -
1500 api calls
start at 10:05:57 end at 10:46:11
Total time - 40mins and 14 secs
Each api call - 1.609 secs

For 1,000.000 items -
2000 api calls
start at 10:05:57 end at 11:24:08
Total time - 1 hour 18mins and 11 secs
Each api call - 2.345 secs


P.S Note:

1) looks like the performance is better for api calls after back porting. Please refer to previous comments for performance results before the back porting was done 

2) The time taking for each api call increases as the size increases

**Comment by jobinthomasnypl** [comment]
Responded to Milton
