### ISSUE TITLE
Work with devops for deploying items pusher and receiver services

### ISSUE THREAD

**Issue by jobinthomasnypl** [NYPL-discovery/discovery-general#8]

**Comment by jobinthomasnypl** [comment]
There are two steps to this:

1) Add the environment variables needed
2) Deploy the services using puppet

**Comment by jobinthomasnypl** [comment]
Created ticket - https://jira.nypl.org/browse/SEB-689

**Comment by jobinthomasnypl** [comment]
Hi @0ara0 ,
Will you be able to check with devops to see what's the status for these issues.

**Comment by 0ara0** [comment]
Pinged tickets 
https://jira.nypl.org/browse/SEB-689
https://jira.nypl.org/browse/SEB-690
