### ISSUE TITLE
entify locations

### ISSUE THREAD

**Issue by nonword** [NYPL-discovery/discovery-general#9]
Need some representation of locations (incl. pickup locations) in Discovery store so they're available in the front-end.

https://docs.google.com/spreadsheets/d/1pwnVvVX_M22wHW3Mc_DzVYYGHQ9EiSFtFQLjqc2DePw/edit#gid=13

**Comment by saverkamp** [comment]
This should be an entity with the following properties?
- code
- branch/collection label
- research or branch
- current location (is this relative to branch/collection?)

**Comment by saverkamp** [comment]
I drafted up a possible entity (based on skos:Concept) for Location at: https://docs.google.com/spreadsheets/d/1qTjXqCO4eusaxr6MGpb7ns4u6k8hmg0s6LzJWvHhmHI/edit#gid=493047939

Here are a couple of example Locations:

@prefix nypl: <http://data.nypl.org/nypl-core/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<http://data.nypl.org/locations/myh11>
	a nypl:Location ;
	skos:prefLabel "Performing Arts Research Collections - Recorded Sound - Reference" ;
	skos:notation "myh11" ;
	nypl:locationType "Research" ;
	nypl:actualLocation "Open shelf reference-3rd floor" .

<http://data.nypl.org/locations/my>
	a nypl:Location ;
	skos:prefLabel "Performing Arts Library at Lincoln Center" ;
	skos:notation "my" ;
	nypl:locationType "Research" ; 
	nypl:locationType "Branch".

Questions: 
- Is it is okay to use the codes as identifiers in the URIs? (i.e. are the codes subject to change?)
- Will Location type and Actual location always be populated?
- What are all possible values for Location type? (I see only Research, Branch, and both.)

cc @katesweeney @thisismattmiller @nonword

**Comment by saverkamp** [comment]
Adding dcterms:isPartOf to represent parent building. 

ex.
```
@prefix nypl: <http://data.nypl.org/nypl-core/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix dcterms: <http://purl.org/dc/terms/> .

<http://data.nypl.org/locations/myh11>
    a nypl:Location ;
    skos:prefLabel "Performing Arts Research Collections - Recorded Sound - Reference" ;
    skos:notation "myh11" ;
    nypl:locationType "Research" ;
    nypl:actualLocation "Open shelf reference-3rd floor" 
    dcterms:isPartOf <http://data.nypl.org/locations/my> .

<http://data.nypl.org/locations/my>
    a nypl:Location ;
    skos:prefLabel "Performing Arts Library at Lincoln Center" ;
    skos:notation "my" ;
    nypl:locationType "Research" ; 
    nypl:locationType "Branch".
```

**Comment by saverkamp** [comment]
Work continues in https://github.com/NYPL-discovery/discovery-models/issues/12
